[biophysical_constants]
transcription_saturation_constant=0.036                # units: µM
characteristic_transcript_length=1000                  # units: nt 
energy_promoter_state_1=20.0                           # units: kJ/mol
energy_promoter_state_2=-28.8                          # units: kJ/mol

inducer_dissociation_constant=24.19    # units: muM from data for deGFP gene
inducer_cooperativity_parameter=1.12   # units: dimensionless hill coefficient
mRNA_half_life_in_min = 13.5          # units: min
RNAPII_concentration=0.06              # units: µM lower end of data from table
transcription_elongation_rate=720      # units: nt/s lower end of data from table
transcription_time_constant=0.61     # units: dimensionless for deGFP transcription
gene_length_in_nt=690                 # units: nt
#deGFP is used becuase it had the closest gene lenght to our assumed gene